package lab1.mybatis.dao;

import lab1.mybatis.model.Lecturer;
import lab1.mybatis.model.University;
import org.mybatis.cdi.Mapper;

import java.util.List;
import java.util.Set;

@Mapper

public interface UniversityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun May 22 01:44:44 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun May 22 01:44:44 EEST 2022
     */
    int insert(University record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun May 22 01:44:44 EEST 2022
     */
    University selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun May 22 01:44:44 EEST 2022
     */
    List<University> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun May 22 01:44:44 EEST 2022
     */
    int updateByPrimaryKey(University record);

    Set<Lecturer> selectCoursesWithLecturers(int libraryId);

}